name: Ahmet Cecen's Research Blog
markdown: kramdown
input: GFM
url: http://ahmetcecen.github.io/
description: An attempt to track professional progress. 


permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']