name:  Ahmet Cecen's Research - MINED@Gatech
markdown: kramdown
input: GFM
url: http://ahmetcecen.github.io/
description: by Ahmet Cecen. An attempt to track and publish my research progress. 


permalink: /:year/:month/:day/:title/
paginate: 5
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']